# Generated by Django 6.0.1 on 2026-01-20 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the announcement', max_length=200, verbose_name='Title')),
                ('message', models.TextField(help_text='Content of the announcement', verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Priority level of the announcement', max_length=10, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this announcement is currently displayed', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this announcement was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this announcement was last updated', verbose_name='Updated At')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this announcement should start being displayed', verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this announcement should stop being displayed (optional)', null=True, verbose_name='Valid Until')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
