# Generated by Django 6.0.1 on 2026-01-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the research project', max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(help_text='Detailed description of the project objectives and scope', verbose_name='Description')),
                ('abstract', models.TextField(blank=True, help_text='Brief summary of the project', verbose_name='Abstract')),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planning', max_length=20, verbose_name='Status')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='private', max_length=20, verbose_name='Access Level')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for the project', max_length=500, verbose_name='Keywords')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=500, verbose_name='Tags')),
                ('project_url', models.URLField(blank=True, help_text='External URL to project website or repository', verbose_name='Project URL')),
                ('funding_source', models.CharField(blank=True, help_text='Organization or agency funding this project', max_length=200, verbose_name='Funding Source')),
                ('grant_number', models.CharField(blank=True, help_text='Grant or contract number', max_length=100, verbose_name='Grant Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_projects', 'Can manage all projects')],
            },
        ),
    ]
