# Generated by Django 6.0.1 on 2026-01-20 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Users who can collaborate on this project', related_name='collaborated_projects', to=settings.AUTH_USER_MODEL, verbose_name='Collaborators'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(help_text='User who owns and manages this project', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Owner'),
        ),
    ]
