# Generated by Django 6.0.4 on 2026-04-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_membership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectmembership',
            new_name='projects_pr_project_710ab3_idx',
            old_name='projects_pr_project_usr_idx',
        ),
    ]
