[pytest]
DJANGO_SETTINGS_MODULE = main.settings
pythonpath = app
python_files = tests.py test_*.py */tests.py
addopts = -v --tb=short
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning:django
