# Generated by Django 6.0.1 on 2026-01-20 16:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', help_text='Preferred language for the interface', max_length=10, verbose_name='Language')),
                ('email_notifications', models.BooleanField(default=False, help_text='Receive email notifications for comments on your datasets', verbose_name='Email Notifications')),
                ('notify_dataset_updates', models.BooleanField(default=False, help_text='Receive email notifications when datasets you follow are updated', verbose_name='Dataset Updates')),
                ('notify_new_versions', models.BooleanField(default=False, help_text='Receive email notifications when new versions of datasets you follow are published', verbose_name='New Versions')),
                ('notify_comments', models.BooleanField(default=False, help_text='Receive email notifications for comments on your datasets', verbose_name='Comments')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this user has been approved by an administrator', verbose_name='Approved')),
                ('first_login_date', models.DateTimeField(blank=True, help_text="Date of the user's first login", null=True, verbose_name='First Login Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.role')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for this API key (e.g., "My Script", "Production API")', max_length=100, verbose_name='Name')),
                ('key', models.CharField(help_text='The API key value (shown only once when created)', max_length=64, unique=True, verbose_name='API Key')),
                ('prefix', models.CharField(help_text='First 8 characters of the key for identification', max_length=8, verbose_name='Key Prefix')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active and can be used', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this API key was created', verbose_name='Created At')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this API key was last used', null=True, verbose_name='Last Used At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this API key', null=True, verbose_name='Expires At')),
                ('user', models.ForeignKey(help_text='The user who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='user_apikey_key_c2af0e_idx'), models.Index(fields=['user', 'is_active'], name='user_apikey_user_id_7e7a2a_idx')],
            },
        ),
    ]
