# Generated by Django 6.0.4 on 2026-04-22 16:29

import labeling.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
        ('projects', '0004_rename_projects_pr_project_usr_idx_projects_pr_project_710ab3_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annotationdraft',
            name='labeling_draft_task_user_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='labeldataset',
            name='labeling_lbl_dataset_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='labelschema',
            name='labeling_lbl_schema_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='labeling_task_project_inner_id_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='tasklock',
            name='labeling_lock_task_user_uniq',
        ),
        migrations.RenameIndex(
            model_name='annotation',
            new_name='labeling_an_task_id_abca43_idx',
            old_name='labeling_ann_task_st_idx',
        ),
        migrations.RenameIndex(
            model_name='imageasset',
            new_name='labeling_im_dataset_c5fab3_idx',
            old_name='labeling_im_ds_created_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='labeling_ta_project_9e41fa_idx',
            old_name='labeling_task_prj_lbl_idx',
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=models.ImageField(max_length=512, upload_to=labeling.models.image_upload_to, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=labeling.models.thumb_upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='annotationdraft',
            unique_together={('task', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='labeldataset',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='labelschema',
            unique_together={('project', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'inner_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tasklock',
            unique_together={('task', 'user')},
        ),
    ]
