# Generated by Django 6.0 — single labeling setup per project (no LabelSchema.version)

from django.db import migrations, models


def consolidate_label_schemata(apps, schema_editor):
    LabelSchema = apps.get_model('labeling', 'LabelSchema')
    Task = apps.get_model('labeling', 'Task')
    for pid in LabelSchema.objects.values_list('project_id', flat=True).distinct():
        rows = list(
            LabelSchema.objects.filter(project_id=pid).order_by('-is_active', '-version', '-id')
        )
        if len(rows) <= 1:
            continue
        keeper = None
        for r in rows:
            if r.is_active:
                keeper = r
                break
        if keeper is None:
            keeper = rows[0]
        other_ids = [r.pk for r in rows if r.pk != keeper.pk]
        Task.objects.filter(schema_id__in=other_ids).update(schema_id=keeper.pk)
        LabelSchema.objects.filter(pk__in=other_ids).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('labeling', '0003_labelschema_selected_for_labeling'),
    ]

    operations = [
        migrations.RunPython(consolidate_label_schemata, noop_reverse),
        migrations.AlterUniqueTogether(
            name='labelschema',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='labelschema',
            name='version',
        ),
        migrations.AddConstraint(
            model_name='labelschema',
            constraint=models.UniqueConstraint(
                fields=('project',), name='labeling_labelschema_project_uniq'
            ),
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='schema_version',
        ),
        migrations.AlterModelOptions(
            name='labelschema',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Label schema',
                'verbose_name_plural': 'Label schemata',
            },
        ),
    ]
